// A1 golden-vector cross-check: the C++ OsqpSolver must reproduce the
// Python AdmmQp reference solution on the SAME condensed MPC problem
// (straight line, N=25, fixed x0).  Golden file generated by
// mpc_core/tools/generate_qp_golden.py (whitespace format, %.17g).
// Registered only when LINEAR_MPC_WITH_OSQP is ON.
#include <cmath>
#include <cstdio>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

#include "linear_mpc_controller/mpc/qp_problem.hpp"

using namespace linear_mpc_controller;

namespace
{
bool readScalars(std::ifstream & f, std::vector<double> & out, std::size_t n)
{
  out.resize(n);
  for (std::size_t i = 0; i < n; ++i) {
    if (!(f >> out[i])) return false;
  }
  return true;
}
}  // namespace

int main()
{
  std::ifstream f(GOLDEN_FILE);
  if (!f) {
    std::printf("cannot open " GOLDEN_FILE "\n");
    return 2;
  }
  long n = 0, m = 0;
  if (!(f >> n >> m) || n <= 0 || m <= 0) {
    std::printf("bad golden header\n");
    return 2;
  }

  std::vector<double> Hh, qv, Cv, lv, uv, xg;
  if (!readScalars(f, Hh, static_cast<std::size_t>(n) * n) ||
    !readScalars(f, qv, static_cast<std::size_t>(n)) ||
    !readScalars(f, Cv, static_cast<std::size_t>(m) * n) ||
    !readScalars(f, lv, static_cast<std::size_t>(m)) ||
    !readScalars(f, uv, static_cast<std::size_t>(m)) ||
    !readScalars(f, xg, static_cast<std::size_t>(n)))
  {
    std::printf("golden file truncated\n");
    return 2;
  }

  using RowMajorMatrixXd =
    Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>;
  // golden file stores matrices row-major
  Eigen::MatrixXd H = Eigen::Map<RowMajorMatrixXd>(Hh.data(), n, n);
  Eigen::VectorXd q = Eigen::Map<Eigen::VectorXd>(qv.data(), n);
  Eigen::MatrixXd C = Eigen::Map<RowMajorMatrixXd>(Cv.data(), m, n);
  Eigen::VectorXd l = Eigen::Map<Eigen::VectorXd>(lv.data(), m);
  Eigen::VectorXd u = Eigen::Map<Eigen::VectorXd>(uv.data(), m);
  Eigen::VectorXd x_golden = Eigen::Map<Eigen::VectorXd>(xg.data(), n);

  auto solver = makeDefaultSolver(4000, 1e-8, 1e-7);
  auto sol = solver->solve(H, q, C, l, u, Eigen::VectorXd::Zero(n));
  if (sol.status != QpSolution::Status::kSolved &&
    sol.status != QpSolution::Status::kApproximate)
  {
    std::printf("FAIL: OSQP did not solve the golden problem\n");
    return 1;
  }

  const double dx_max = (sol.u - x_golden).cwiseAbs().maxCoeff();
  const double obj_golden = x_golden.dot(H * x_golden) / 2.0 + q.dot(x_golden);
  const double obj_osqp = sol.u.dot(H * sol.u) / 2.0 + q.dot(sol.u);
  std::printf("golden cross-check: max|dx|=%.3e obj_golden=%.6f obj_osqp=%.6f\n",
    dx_max, obj_golden, obj_osqp);

  if (dx_max > 1e-2 || std::abs(obj_osqp - obj_golden) >
    1e-4 * (1.0 + std::abs(obj_golden)))
  {
    std::printf("FAIL: solution deviates from Python AdmmQp golden\n");
    return 1;
  }
  std::printf("PASS: OsqpSolver matches Python AdmmQp golden\n");
  return 0;
}
